2019-06-20 16:49:55,564 Script started with -77.055, 39.121, -76.305, 39.508' parameters
2019-06-20 16:49:55,565 Exception on /coords [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 294, in pipeline
    location[3] = float(location[3])
ValueError: could not convert string to float: "39.508'"
2019-06-20 16:49:55,577 127.0.0.1 - - [20/Jun/2019 16:49:55] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508%27 HTTP/1.1" 500 -
2019-06-20 16:49:55,583 Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 294, in pipeline
    location[3] = float(location[3])
ValueError: could not convert string to float: "39.508'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1767, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
TypeError: server_error() takes 0 positional arguments but 1 was given
2019-06-20 16:49:55,638 127.0.0.1 - - [20/Jun/2019 16:49:55] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-20 16:50:03,167 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-20 16:50:03,167 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-20 16:50:03,170 Map Successfully Converted to .o5m
2019-06-20 16:50:03,170 convertosm: 0.00257110595703125
2019-06-20 16:50:03,170 Starting osmfilter32 on app/o5m_Temp.o5m
2019-06-20 16:50:03,179 Filtering Complete
2019-06-20 16:50:03,179 filterosm: 0.009068489074707031
2019-06-20 16:50:03,179 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-20 16:50:03,180 Exception on /coords [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 323, in pipeline
    test2 = osm_to_adj.main(filename, 4)
  File "/home/nightt/flask_test/app/osm_to_adj.py", line 217, in main
    f = io.open(input_filename,encoding='utf-8')           # open file
FileNotFoundError: [Errno 2] No such file or directory: 'app/xml_Temp.xml'
2019-06-20 16:50:03,182 127.0.0.1 - - [20/Jun/2019 16:50:03] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 500 -
2019-06-20 16:50:03,188 Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 323, in pipeline
    test2 = osm_to_adj.main(filename, 4)
  File "/home/nightt/flask_test/app/osm_to_adj.py", line 217, in main
    f = io.open(input_filename,encoding='utf-8')           # open file
FileNotFoundError: [Errno 2] No such file or directory: 'app/xml_Temp.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1767, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
TypeError: server_error() takes 0 positional arguments but 1 was given
2019-06-20 16:50:03,206 127.0.0.1 - - [20/Jun/2019 16:50:03] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-20 16:50:17,753 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-20 16:50:17,754 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-20 16:50:17,757 Map Successfully Converted to .o5m
2019-06-20 16:50:17,758 convertosm: 0.00406193733215332
2019-06-20 16:50:17,758 Starting osmfilter32 on app/o5m_Temp.o5m
2019-06-20 16:50:17,761 Filtering Complete
2019-06-20 16:50:17,761 filterosm: 0.003675699234008789
2019-06-20 16:50:17,762 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-20 16:50:17,762 Exception on /coords [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 323, in pipeline
    test2 = osm_to_adj.main(filename, 4)
  File "/home/nightt/flask_test/app/osm_to_adj.py", line 217, in main
    f = io.open(input_filename,encoding='utf-8')           # open file
FileNotFoundError: [Errno 2] No such file or directory: 'app/xml_Temp.xml'
2019-06-20 16:50:17,771 127.0.0.1 - - [20/Jun/2019 16:50:17] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 500 -
2019-06-20 16:50:17,776 Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 323, in pipeline
    test2 = osm_to_adj.main(filename, 4)
  File "/home/nightt/flask_test/app/osm_to_adj.py", line 217, in main
    f = io.open(input_filename,encoding='utf-8')           # open file
FileNotFoundError: [Errno 2] No such file or directory: 'app/xml_Temp.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1767, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
TypeError: server_error() takes 0 positional arguments but 1 was given
2019-06-20 16:50:17,803 127.0.0.1 - - [20/Jun/2019 16:50:17] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-20 16:51:04,275 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-20 16:51:04,275 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-20 16:51:14,609 Map Successfully Converted to .o5m
2019-06-20 16:51:14,609 convertosm: 10.334233522415161
2019-06-20 16:51:14,609 Starting osmfilter32 on app/o5m_Temp.o5m
2019-06-20 16:51:14,835 Filtering Complete
2019-06-20 16:51:14,835 filterosm: 0.22588038444519043
2019-06-20 16:51:14,835 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-20 16:51:19,519 osm run1: 4.683732986450195
2019-06-20 16:51:19,519 OSM to Adj complete
2019-06-20 16:51:19,539 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 4.703267335891724 seconds
2019-06-20 16:51:19,554 127.0.0.1 - - [20/Jun/2019 16:51:19] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 200 -
2019-06-20 16:51:22,582 127.0.0.1 - - [20/Jun/2019 16:51:22] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-21 09:32:34,786 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-21 09:32:34,787 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-21 09:32:45,266 Map Successfully Converted to .o5m
2019-06-21 09:32:45,267 convertosm: 10.479870557785034
2019-06-21 09:32:45,267 Starting osmfilter32 on app/o5m_Temp.o5m
2019-06-21 09:32:45,492 Filtering Complete
2019-06-21 09:32:45,493 filterosm: 0.2261207103729248
2019-06-21 09:32:45,493 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-21 09:32:50,111 osm run1: 4.617498159408569
2019-06-21 09:32:50,111 OSM to Adj complete
2019-06-21 09:32:50,133 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 4.639627456665039 seconds
2019-06-21 09:32:50,147 127.0.0.1 - - [21/Jun/2019 09:32:50] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 200 -
2019-06-21 09:32:53,140 127.0.0.1 - - [21/Jun/2019 09:32:53] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-21 09:34:30,590 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-21 09:34:30,591 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-21 09:34:40,462 Map Successfully Converted to .o5m
2019-06-21 09:34:40,463 convertosm: 9.872016429901123
2019-06-21 09:34:40,463 Starting osmfilter32 on app/o5m_Temp.o5m
2019-06-21 09:34:40,695 Filtering Complete
2019-06-21 09:34:40,695 filterosm: 0.23219013214111328
2019-06-21 09:34:40,695 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-21 09:34:45,078 osm run1: 4.382192611694336
2019-06-21 09:34:45,078 OSM to Adj complete
2019-06-21 09:34:45,842 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 5.146604537963867 seconds
2019-06-21 09:34:46,420 127.0.0.1 - - [21/Jun/2019 09:34:46] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 200 -
2019-06-21 09:34:52,862 127.0.0.1 - - [21/Jun/2019 09:34:52] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-21 10:41:12,308 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-21 10:41:12,309 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-21 10:41:12,312 Map Successfully Converted to .o5m
2019-06-21 10:41:12,312 convertosm: 0.0031647682189941406
2019-06-21 10:41:12,312 Starting osmfilter32 on app/o5m_Temp.o5m
2019-06-21 10:41:12,316 Filtering Complete
2019-06-21 10:41:12,316 filterosm: 0.004217863082885742
2019-06-21 10:41:12,316 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-21 10:41:12,317 Exception on /coords [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 326, in pipeline
    test2 = osm_to_adj.main(filename, 4)
  File "/home/nightt/flask_test/app/osm_to_adj.py", line 217, in main
    f = io.open(input_filename,encoding='utf-8')           # open file
FileNotFoundError: [Errno 2] No such file or directory: 'app/xml_Temp.xml'
2019-06-21 10:41:12,327 127.0.0.1 - - [21/Jun/2019 10:41:12] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 500 -
2019-06-21 10:41:12,333 Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 326, in pipeline
    test2 = osm_to_adj.main(filename, 4)
  File "/home/nightt/flask_test/app/osm_to_adj.py", line 217, in main
    f = io.open(input_filename,encoding='utf-8')           # open file
FileNotFoundError: [Errno 2] No such file or directory: 'app/xml_Temp.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1767, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
TypeError: server_error() takes 0 positional arguments but 1 was given
2019-06-21 10:41:14,470 127.0.0.1 - - [21/Jun/2019 10:41:14] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-21 10:42:09,095 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-21 10:42:09,095 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-21 10:42:19,356 Map Successfully Converted to .o5m
2019-06-21 10:42:19,356 convertosm: 10.260590314865112
2019-06-21 10:42:19,356 Starting osmfilter32 on app/o5m_Temp.o5m
2019-06-21 10:42:19,595 Filtering Complete
2019-06-21 10:42:19,595 filterosm: 0.23925304412841797
2019-06-21 10:42:19,596 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-21 10:42:24,405 osm run1: 4.809032201766968
2019-06-21 10:42:24,405 OSM to Adj complete
2019-06-21 10:42:25,089 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 5.493472337722778 seconds
2019-06-21 10:42:25,660 127.0.0.1 - - [21/Jun/2019 10:42:25] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 200 -
2019-06-21 10:42:32,498 127.0.0.1 - - [21/Jun/2019 10:42:32] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-21 10:42:33,412 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-21 10:42:33,413 Exception on /coords [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 300, in pipeline
    f = open('data.json')
FileNotFoundError: [Errno 2] No such file or directory: 'data.json'
2019-06-21 10:42:33,420 127.0.0.1 - - [21/Jun/2019 10:42:33] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 500 -
2019-06-21 10:42:33,425 Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nightt/flask_test/app/routes.py", line 59, in coordsInput
    return pipeline(input_Value)
  File "/home/nightt/flask_test/app/routes.py", line 300, in pipeline
    f = open('data.json')
FileNotFoundError: [Errno 2] No such file or directory: 'data.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1767, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
TypeError: server_error() takes 0 positional arguments but 1 was given
2019-06-21 10:42:33,554 127.0.0.1 - - [21/Jun/2019 10:42:33] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-21 10:43:18,727 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-21 10:43:18,862 Exception on /coords [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1835, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1850, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2001, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.
2019-06-21 10:43:18,868 127.0.0.1 - - [21/Jun/2019 10:43:18] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 500 -
2019-06-21 10:43:18,875 Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1835, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1850, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2001, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1767, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
TypeError: server_error() takes 0 positional arguments but 1 was given
2019-06-21 10:43:18,893 127.0.0.1 - - [21/Jun/2019 10:43:18] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-21 10:44:33,786 Script started with -77.055, 39.121, -76.305, 39.508 parameters
2019-06-21 10:44:34,539 127.0.0.1 - - [21/Jun/2019 10:44:34] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508 HTTP/1.1" 200 -
2019-06-21 10:44:39,846 127.0.0.1 - - [21/Jun/2019 10:44:39] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-26 17:36:25,029  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-26 17:37:13,625  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-26 17:37:27,700  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-26 17:37:58,594 127.0.0.1 - - [26/Jun/2019 17:37:58] "GET / HTTP/1.1" 200 -
2019-06-26 17:37:58,652 127.0.0.1 - - [26/Jun/2019 17:37:58] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-26 17:38:19,420 Next wakeup is due at 2019-07-02 02:00:00-04:00 (in 462100.579862 seconds)
2019-06-26 17:38:19,433 Converting and filtering error
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 253, in update
    os.rename("app/map_files/download/" + sub["file_name"], "app/map_files/download/temp/" + sub["file_name"])
FileNotFoundError: [Errno 2] No such file or directory: 'app/map_files/download/north-america-latest.osm.pbf' -> 'app/map_files/download/temp/north-america-latest.osm.pbf'
2019-06-26 17:38:19,695 Update file read exception
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 265, in update
    os.rename("app/map_files/download/" + sub["file_name"], "app/map_files/" + sub["file_name"])
FileNotFoundError: [Errno 2] No such file or directory: 'app/map_files/download/north-america-latest.osm.pbf' -> 'app/map_files/north-america-latest.osm.pbf'
2019-06-26 17:38:19,705  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-26 17:39:50,348 Converting and filtering error
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 253, in update
    os.rename("app/map_files/download/" + sub["file_name"], "app/map_files/download/temp/" + sub["file_name"])
FileNotFoundError: [Errno 2] No such file or directory: 'app/map_files/download/north-america-latest.osm.pbf' -> 'app/map_files/download/temp/north-america-latest.osm.pbf'
2019-06-26 17:39:50,601 Update file read exception
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 265, in update
    os.rename("app/map_files/download/" + sub["file_name"], "app/map_files/" + sub["file_name"])
FileNotFoundError: [Errno 2] No such file or directory: 'app/map_files/download/north-america-latest.osm.pbf' -> 'app/map_files/north-america-latest.osm.pbf'
2019-06-26 17:39:50,612  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-26 17:41:23,313 Converting and filtering error
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 257, in update
    os.remove("app/o5m_Temp.o5m")
FileNotFoundError: [Errno 2] No such file or directory: 'app/o5m_Temp.o5m'
2019-06-26 17:41:23,329  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-26 17:41:47,496 Update file read exception
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 223, in update
    os.mkdir("app/map_files/download")
FileExistsError: [Errno 17] File exists: 'app/map_files/download'
2019-06-26 17:41:47,505  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 11:47:59,882 Update file read exception
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 223, in update
    os.mkdir("app/map_files/download")
FileExistsError: [Errno 17] File exists: 'app/map_files/download'
2019-06-27 11:47:59,892  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 11:49:11,398 Update file read exception
Traceback (most recent call last):
  File "/home/nightt/flask_test/app/routes.py", line 223, in update
    os.mkdir("app/map_files/download")
FileExistsError: [Errno 17] File exists: 'app/map_files/download'
2019-06-27 11:49:11,406  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 12:01:19,090  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 12:14:03,101 -----------------------------------------------------------------
2019-06-27 12:14:03,101 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:14:03,101 Script using street detail level of default (full detail)
2019-06-27 12:14:03,101 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:14:13,606 Map Successfully Converted to .o5m in: 10.504961013793945
2019-06-27 12:14:13,607 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway=motorway =trunk =primary =secondary =tertiary =unclassified =primary_link =secondary_link =tertiary_link =trunk_link =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:14:13,834 Filtering Complete in: 0.22683954238891602
2019-06-27 12:14:13,834 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:14:18,660 OSM to Adj complete in: : 4.825176239013672
2019-06-27 12:14:19,312 Hash: 18295a8c2e3dd5a83907f36e4240899e
2019-06-27 12:14:19,317 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 5.482264041900635 seconds
2019-06-27 12:14:19,870 127.0.0.1 - - [27/Jun/2019 12:14:19] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=motorway HTTP/1.1" 200 -
2019-06-27 12:14:25,896 127.0.0.1 - - [27/Jun/2019 12:14:25] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:15:00,543 -----------------------------------------------------------------
2019-06-27 12:15:00,543 Script started with Box: -77.045, 39.121, -76.305, 39.508 bounds
2019-06-27 12:15:00,543 Script using street detail level of default (full detail)
2019-06-27 12:15:00,543 Converting -77.045, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:15:11,305 Map Successfully Converted to .o5m in: 10.761654138565063
2019-06-27 12:15:11,305 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway=motorway =trunk =primary =secondary =tertiary =unclassified =primary_link =secondary_link =tertiary_link =trunk_link =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:15:11,540 Filtering Complete in: 0.2347395420074463
2019-06-27 12:15:11,540 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:15:15,910 OSM to Adj complete in: : 4.369687795639038
2019-06-27 12:15:16,542 Hash: 0487b880010ea745e2dce714be76b988
2019-06-27 12:15:16,546 Map file created with bounds: [-77.045, 39.121, -76.305, 39.508] in 5.005111217498779 seconds
2019-06-27 12:15:17,188 127.0.0.1 - - [27/Jun/2019 12:15:17] "GET /coords?minLon=-77.045&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=default HTTP/1.1" 200 -
2019-06-27 12:15:20,577 127.0.0.1 - - [27/Jun/2019 12:15:20] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:15:51,195  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 12:15:55,725 -----------------------------------------------------------------
2019-06-27 12:15:55,725 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:15:55,725 Script using street detail level of default (full detail)
2019-06-27 12:15:55,725 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:16:07,221 Map Successfully Converted to .o5m in: 11.495012283325195
2019-06-27 12:16:07,221 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway=motorway =trunk =primary =secondary =tertiary =unclassified =primary_link =secondary_link =tertiary_link =trunk_link =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:16:07,470 Filtering Complete in: 0.24887871742248535
2019-06-27 12:16:07,470 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:16:12,448 OSM to Adj complete in: : 4.977954864501953
2019-06-27 12:16:13,148 Hash: 18295a8c2e3dd5a83907f36e4240899e
2019-06-27 12:16:13,152 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 5.681610822677612 seconds
2019-06-27 12:16:13,706 127.0.0.1 - - [27/Jun/2019 12:16:13] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=motorway HTTP/1.1" 200 -
2019-06-27 12:16:19,897 127.0.0.1 - - [27/Jun/2019 12:16:19] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:16:46,363 Next wakeup is due at 2019-07-02 02:00:00-04:00 (in 394993.637006 seconds)
2019-06-27 12:16:46,371  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 12:16:50,317 -----------------------------------------------------------------
2019-06-27 12:16:50,317 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:16:50,317 Script using street detail level of default (full detail)
2019-06-27 12:16:50,317 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:17:00,486 Map Successfully Converted to .o5m in: 10.168345928192139
2019-06-27 12:17:00,486 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway=motorway =trunk =primary =secondary =tertiary =unclassified =primary_link =secondary_link =tertiary_link =trunk_link =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:17:00,718 Filtering Complete in: 0.2319040298461914
2019-06-27 12:17:00,718 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:17:06,573 OSM to Adj complete in: : 5.854227066040039
2019-06-27 12:17:07,332 Hash: 18295a8c2e3dd5a83907f36e4240899e
2019-06-27 12:17:07,336 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 6.617837190628052 seconds
2019-06-27 12:17:07,957 127.0.0.1 - - [27/Jun/2019 12:17:07] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=motorway HTTP/1.1" 200 -
2019-06-27 12:17:14,703 127.0.0.1 - - [27/Jun/2019 12:17:14] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:18:28,081  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 12:18:32,714 -----------------------------------------------------------------
2019-06-27 12:18:32,714 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:18:32,714 Script using street detail level of: motorway
2019-06-27 12:18:32,714 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:18:42,889 Map Successfully Converted to .o5m in: 10.174464702606201
2019-06-27 12:18:42,889 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway =motorway =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:18:43,121 Filtering Complete in: 0.23231005668640137
2019-06-27 12:18:43,122 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:18:47,623 OSM to Adj complete in: : 4.501544952392578
2019-06-27 12:18:48,251 Hash: 18295a8c2e3dd5a83907f36e4240899e
2019-06-27 12:18:48,255 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 5.1329967975616455 seconds
2019-06-27 12:18:48,836 127.0.0.1 - - [27/Jun/2019 12:18:48] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=motorway HTTP/1.1" 200 -
2019-06-27 12:18:54,359 127.0.0.1 - - [27/Jun/2019 12:18:54] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:19:32,838  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 12:19:37,907 -----------------------------------------------------------------
2019-06-27 12:19:37,907 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:19:37,907 Script using street detail level of: motorway
2019-06-27 12:19:37,908 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:19:48,264 Map Successfully Converted to .o5m in: 10.355975151062012
2019-06-27 12:19:48,264 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway =motorway =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:19:48,498 Filtering Complete in: 0.2337048053741455
2019-06-27 12:19:48,498 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:19:53,458 OSM to Adj complete in: : 4.959877014160156
2019-06-27 12:19:54,113 Hash: 18295a8c2e3dd5a83907f36e4240899e
2019-06-27 12:19:54,113 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 5.614725589752197 seconds
2019-06-27 12:19:54,654 127.0.0.1 - - [27/Jun/2019 12:19:54] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=motorway HTTP/1.1" 200 -
2019-06-27 12:20:01,017 127.0.0.1 - - [27/Jun/2019 12:20:01] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:21:56,084 -----------------------------------------------------------------
2019-06-27 12:21:56,084 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:21:56,084 Script using street detail level of default (full detail)
2019-06-27 12:21:56,733 127.0.0.1 - - [27/Jun/2019 12:21:56] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=default HTTP/1.1" 200 -
2019-06-27 12:22:03,166 127.0.0.1 - - [27/Jun/2019 12:22:03] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:22:05,634 -----------------------------------------------------------------
2019-06-27 12:22:05,634 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:22:05,634 Script using street detail level of default (full detail)
2019-06-27 12:22:05,634 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:22:16,408 Map Successfully Converted to .o5m in: 10.774092674255371
2019-06-27 12:22:16,409 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway=motorway =trunk =primary =secondary =tertiary =unclassified =primary_link =secondary_link =tertiary_link =trunk_link =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:22:16,667 Filtering Complete in: 0.25769782066345215
2019-06-27 12:22:16,668 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:22:20,978 OSM to Adj complete in: : 4.310058355331421
2019-06-27 12:22:21,620 Hash: 18295a8c2e3dd5a83907f36e4240899e
2019-06-27 12:22:21,620 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 4.952436447143555 seconds
2019-06-27 12:22:22,292 127.0.0.1 - - [27/Jun/2019 12:22:22] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=default HTTP/1.1" 200 -
2019-06-27 12:22:28,500 127.0.0.1 - - [27/Jun/2019 12:22:28] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:23:24,402 -----------------------------------------------------------------
2019-06-27 12:23:24,402 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:23:24,402 Script using street detail level of: motorway
2019-06-27 12:23:24,402 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:23:34,603 Map Successfully Converted to .o5m in: 10.200216054916382
2019-06-27 12:23:34,603 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway =motorway =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:23:34,858 Filtering Complete in: 0.2550959587097168
2019-06-27 12:23:34,859 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:23:39,324 OSM to Adj complete in: : 4.464867830276489
2019-06-27 12:23:39,964 Hash: 18295a8c2e3dd5a83907f36e4240899e
2019-06-27 12:23:39,964 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 5.105270147323608 seconds
2019-06-27 12:23:40,505 127.0.0.1 - - [27/Jun/2019 12:23:40] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=motorway HTTP/1.1" 200 -
2019-06-27 12:23:46,365 127.0.0.1 - - [27/Jun/2019 12:23:46] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:27:34,179  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-06-27 12:27:42,644 -----------------------------------------------------------------
2019-06-27 12:27:42,645 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:27:42,645 Script using street detail level of: motorway
2019-06-27 12:27:42,645 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:27:53,193 Map Successfully Converted to .o5m in: 10.548226356506348
2019-06-27 12:27:53,194 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway=motorway =motorway_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:27:53,302 Filtering Complete in: 0.10829639434814453
2019-06-27 12:27:53,302 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:27:54,038 OSM to Adj complete in: : 0.7358171939849854
2019-06-27 12:27:54,137 Hash: 99e89f214bca2598004f78fa2afb1c91
2019-06-27 12:27:54,137 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 0.8344392776489258 seconds
2019-06-27 12:27:54,214 127.0.0.1 - - [27/Jun/2019 12:27:54] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=motorway HTTP/1.1" 200 -
2019-06-27 12:27:54,968 127.0.0.1 - - [27/Jun/2019 12:27:54] "GET /favicon.ico HTTP/1.1" 200 -
2019-06-27 12:28:17,359 -----------------------------------------------------------------
2019-06-27 12:28:17,359 Script started with Box: -77.055, 39.121, -76.305, 39.508 bounds
2019-06-27 12:28:17,359 Script using street detail level of: primary
2019-06-27 12:28:17,359 Converting -77.055, 39.121, -76.305, 39.508 map to .o5m
2019-06-27 12:28:27,716 Map Successfully Converted to .o5m in: 10.357498168945312
2019-06-27 12:28:27,717 Starting osmfilter32 on app/o5m_Temp.o5m with filter command app/osm_converts/osmfilter32 app/o5m_Temp.o5m --keep="highway=motorway =motorway_link =trunk =trunk_link =primary =primary_link" --drop-version -o=app/xml_Temp.xml
2019-06-27 12:28:27,858 Filtering Complete in: 0.14138269424438477
2019-06-27 12:28:27,859 Starting OSM to Adj Convert on app/xml_Temp.xml
2019-06-27 12:28:29,453 OSM to Adj complete in: : 1.5945241451263428
2019-06-27 12:28:29,661 Hash: 55a0df9eafd3bdcc07d3287b367cade6
2019-06-27 12:28:29,661 Map file created with bounds: [-77.055, 39.121, -76.305, 39.508] in 1.8024537563323975 seconds
2019-06-27 12:28:29,838 127.0.0.1 - - [27/Jun/2019 12:28:29] "GET /coords?minLon=-77.055&minLat=39.121&maxLon=-76.305&maxLat=39.508&level=primary HTTP/1.1" 200 -
2019-06-27 12:28:31,282 127.0.0.1 - - [27/Jun/2019 12:28:31] "GET /favicon.ico HTTP/1.1" 200 -
